print(
    "\n19.292395 = sum of:\n  3.6837666 = max plus 0.1 times others of:\n    2.8151627 = weight(summary:carot in 282) "
    "[SchemaSimilarity], result of:\n      2.8151627 = score(freq=1.0), computed as boost * idf * tf from:\n        "
    "5.5441213 = idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:\n          18 = n, number of documents "
    "containing term\n          4730 = N, total number of documents with field\n        0.50777435 = tf, computed as "
    "freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:\n          1.0 = freq, occurrences of term within document\n "
    "         1.2 = k1, term saturation parameter\n          0.75 = b, length normalization parameter\n          27.0 "
    "= dl, length of field\n          36.302326 = avgdl, average length of field\n    3.1217256 = weight(title:carot "
    "in 282) [SchemaSimilarity], result of:\n      3.1217256 = score(freq=1.0), computed as boost * idf * tf from:\n  "
    "      5.796791 = idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:\n          14 = n, number of "
    "documents containing term\n          4773 = N, total number of documents with field\n        0.53852654 = tf, "
    "computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:\n          1.0 = freq, occurrences of term "
    "within document\n          1.2 = k1, term saturation parameter\n          0.75 = b, length normalization "
    "parameter\n          3.0 = dl, length of field\n          4.848104 = avgdl, average length of field\n    "
    "2.8052485 = weight(html_mainpart:carot in 282) [SchemaSimilarity], result of:\n      2.8052485 = score("
    "freq=17.0), computed as boost * idf * tf from:\n        2.9436324 = idf, computed as log(1 + (N - n + 0.5) / (n "
    "+ 0.5)) from:\n          228 = n, number of documents containing term\n          4337 = N, total number of "
    "documents with field\n        0.95298874 = tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:\n "
    "         17.0 = freq, occurrences of term within document\n          1.2 = k1, term saturation parameter\n       "
    "   0.75 = b, length normalization parameter\n          440.0 = dl, length of field (approximate)\n          "
    "735.21814 = avgdl, average length of field\n  15.608628 = weight(title:carot in 282) [SchemaSimilarity], "
    "result of:\n    15.608628 = score(freq=1.0), computed as boost * idf * tf from:\n      5.0 = boost\n      "
    "5.796791 = idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:\n        14 = n, number of documents "
    "containing term\n        4773 = N, total number of documents with field\n      0.53852654 = tf, computed as freq "
    "/ (freq + k1 * (1 - b + b * dl / avgdl)) from:\n        1.0 = freq, occurrences of term within document\n        "
    "1.2 = k1, term saturation parameter\n        0.75 = b, length normalization parameter\n        3.0 = dl, "
    "length of field\n        4.848104 = avgdl, average length of field\n")

print("||||||||||||||||||||||||||||||||||||||||||||||||||\n")

print("\n15.294412 = sum of:\n  3.286994 = max plus 0.1 times others of:\n    2.746025 = weight(summary:carot in "
      "1962) [SchemaSimilarity], result of:\n      2.746025 = score(freq=1.0), computed as boost * idf * tf from:\n   "
      "     5.5441213 = idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:\n          18 = n, "
      "number of documents containing term\n          4730 = N, total number of documents with field\n        "
      "0.49530393 = tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:\n          1.0 = freq, "
      "occurrences of term within document\n          1.2 = k1, term saturation parameter\n          0.75 = b, "
      "length normalization parameter\n          29.0 = dl, length of field\n          36.302326 = avgdl, "
      "average length of field\n    2.4014838 = weight(title:carot in 1962) [SchemaSimilarity], result of:\n      "
      "2.4014838 = score(freq=1.0), computed as boost * idf * tf from:\n        5.796791 = idf, computed as log(1 + ("
      "N - n + 0.5) / (n + 0.5)) from:\n          14 = n, number of documents containing term\n          4773 = N, "
      "total number of documents with field\n        0.41427815 = tf, computed as freq / (freq + k1 * (1 - b + b * dl "
      "/ avgdl)) from:\n          1.0 = freq, occurrences of term within document\n          1.2 = k1, "
      "term saturation parameter\n          0.75 = b, length normalization parameter\n          6.0 = dl, "
      "length of field\n          4.848104 = avgdl, average length of field\n    2.772243 = weight("
      "html_mainpart:carot in 1962) [SchemaSimilarity], result of:\n      2.772243 = score(freq=18.0), computed as "
      "boost * idf * tf from:\n        2.9436324 = idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:\n        "
      "  228 = n, number of documents containing term\n          4337 = N, total number of documents with field\n     "
      "   0.9417763 = tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:\n          18.0 = freq, "
      "occurrences of term within document\n          1.2 = k1, term saturation parameter\n          0.75 = b, "
      "length normalization parameter\n          664.0 = dl, length of field (approximate)\n          735.21814 = "
      "avgdl, average length of field\n  12.007418 = weight(title:carot in 1962) [SchemaSimilarity], result of:\n    "
      "12.007418 = score(freq=1.0), computed as boost * idf * tf from:\n      5.0 = boost\n      5.796791 = idf, "
      "computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:\n        14 = n, number of documents containing term\n    "
      "    4773 = N, total number of documents with field\n      0.41427815 = tf, computed as freq / (freq + k1 * (1 "
      "- b + b * dl / avgdl)) from:\n        1.0 = freq, occurrences of term within document\n        1.2 = k1, "
      "term saturation parameter\n        0.75 = b, length normalization parameter\n        6.0 = dl, "
      "length of field\n        4.848104 = avgdl, average length of field\n")
